### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by fbonzon** [imelgrat/google-time-zone#3]
Can you tag a new release, so that we can more easily use this library with composer? Because of the autoloader issue (already fixed in master) , it's currently unusable.

**Comment by imelgrat** [comment]
Thank you François! I'm new to Github (always worked with SVN). I just created a new release, the autoloader should work now. Let me know if it doesn't.

**Comment by fbonzon** [comment]
Packagist still doesn't show the latest version: https://packagist.org/packages/imelgrat/google-time-zone

You need to update this version in Packagist website, and configure GitHub so that is pushes automatically to Packagist when you tag a new release.

**Comment by imelgrat** [comment]
My composer.json was to blame there. I fixed it by removing the version line and created a new release.
